version: '3.9'

services:
  app:
    container_name: todo_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    container_name: todo_db
    image: postgres:16
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - '5433:5432'
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
